spring:
  application:
    name: pet_clinic_jooq

  liquibase:
    change-log: db/changelog/changelog-master.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/pet_clinic
    username: postgres
    password: q1w2e3r4
    driver-class-name: org.postgresql.Driver

server:
  port: 8099
  servlet:
    context-path: /api/clinic/v1

logging:
  level:
    org:
      jooq:
        tools:
          LoggerListener: DEBUG